### ISSUE TITLE
Different pre-commit CI is fighting with each other

### ISSUE THREAD

**Issue by winstonsung** [WeblateOrg/language-data#1434] opened 2024-08-27 19:45 UTC
### Describe the issue

- GitHub Actions - Passed + https://results.pre-commit.ci - Failed + commit

Then

- https://results.pre-commit.ci - committed & passed - GitHub Actions - Now Failed

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

See current pull requests 
- #1430
- #1432
- #1433

**Comment by nijel** [comment] 2024-08-28 05:47
I've noticed that, but didn't investigate the root cause. It seems that `mdformat` behaves inconsistent between environments, perhaps it depends on Python version?

**Comment by nijel** [comment] 2024-08-28 06:04
Should be fixed now by using https://pypi.org/project/mdformat_tables/

**Closed by nijel** 2024-08-28 06:04 UTC
